services:
  ice:
    image: docker.io/oughtinc/ice:0.2.0
    env_file: .env # user should replace this with their own .env file
    restart: on-failure
    volumes:
      # When mounting source code, don't clobber generated directories.
      # https://stackoverflow.com/a/37898591
      - /workspaces/code/.venv/
      - /workspaces/code/ui/node_modules/
      - ../.:/workspaces/code
    ports:
      - "3000:3000"
      - "8935:8935"
