services:
  ice:
    image: docker.io/oughtinc/ice:0.2.0
    container_name: iceapp-dev
    build:
      context: ..
    # pass variables from file to service
    # https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
    env_file: .env
    restart: on-failure
    volumes:
      - ../.:/workspaces/code
      # When mounting source code, don't clobber generated directories.
      # https://stackoverflow.com/a/37898591
      # - /workspaces/${localWorkspaceFolderBasename}/.venv/
      # - /workspaces/${localWorkspaceFolderBasename}/ui/node_modules/
    ports:
      - "3000:3000"
      - "8935:8935"
